/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder */

#ifndef _Included_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
#define _Included_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    createBuilderInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_createBuilderInternal
  (JNIEnv *, jclass);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    releaseBuilderInternal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_releaseBuilderInternal
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    beginPath
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_beginPath
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    addPathPoint
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_addPathPoint
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    endPath
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_endPath
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    build
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_build
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaVertexCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaVertexCount
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaVertexX
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaVertexX
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaVertexY
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaVertexY
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaIndexCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaIndexCount
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaIndex
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaIndex
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaArea
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaArea
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaGridCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaGridCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaGridKey
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaGridKey
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaGridValueCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaGridValueCount
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder
 * Method:    getAreaGridValue
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeLandBuilder_getAreaGridValue
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
