/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lifefesta_drun_server_module_nativemodule_NativeMain */

#ifndef _Included_com_lifefesta_drun_server_module_nativemodule_NativeMain
#define _Included_com_lifefesta_drun_server_module_nativemodule_NativeMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeMain
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeMain_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
