/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lifefesta_drun_server_module_nativemodule_NativeBSDiff */

#ifndef _Included_com_lifefesta_drun_server_module_nativemodule_NativeBSDiff
#define _Included_com_lifefesta_drun_server_module_nativemodule_NativeBSDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeBSDiff
 * Method:    bsdiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeBSDiff_bsdiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_lifefesta_drun_server_module_nativemodule_NativeBSDiff
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_lifefesta_drun_server_module_nativemodule_NativeBSDiff_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
